export const filterOptions = {
  channel: [
    { value: "retail-store", label: "Retail-Store" },
    { value: "online", label: "Online" },
    { value: "wholesale", label: "Wholesale" },
  ],
  department: [
    { value: "d01", label: "D01-Womens Bags" },
    { value: "d02", label: "D02-Mens Shoes" },
    { value: "d03", label: "D03-Home Decor" },
    { value: "d04", label: "D04-Kids Apparel" },
    { value: "d05", label: "D05-Beauty Products" },
    { value: "d06", label: "D06-Accessories" },
    { value: "d07", label: "D07-Electronics" },
    { value: "d08", label: "D08-Books" },
    { value: "d09", label: "D09-Toys" },
    { value: "d10", label: "D10-Pet Supplies" },
    { value: "d11", label: "D11-Automotive" },
    { value: "d12", label: "D12-Furniture" },
    { value: "d13", label: "D13-Garden Supplies" },
    { value: "d14", label: "D14-Jewelry" },
    { value: "d15", label: "D15-Sports Equipment" },
    { value: "d16", label: "D16-Health Products" },
  ],
  class: [
    { value: "class1", label: "Class 1" },
    { value: "class2", label: "Class 2" },
    { value: "class3", label: "Class 3" },
    { value: "class4", label: "Class 4" },
    { value: "class5", label: "Class 5" },
  ],
  silhouette: [
    { value: "silhouette1", label: "Silhouette 1" },
    { value: "silhouette2", label: "Silhouette 2" },
    { value: "silhouette3", label: "Silhouette 3" },
    { value: "silhouette4", label: "Silhouette 4" },
  ],
  subCollect: [
    { value: "sub1", label: "SubCollect 1" },
    { value: "sub2", label: "SubCollect 2" },
    { value: "sub3", label: "SubCollect 3" },
    { value: "sub4", label: "SubCollect 4" },
    { value: "sub5", label: "SubCollect 5" },
  ],
  storeGroup: [
    { value: "group1", label: "Store Group 1" },
    { value: "group2", label: "Store Group 2" },
    { value: "group3", label: "Store Group 3" },
    { value: "group4", label: "Store Group 4" },
  ],
};
